# Generated by Django 2.0.2 on 2020-07-09 17:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('QuestionnaireColorCue', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Classify_And_Learn_Samples_set1',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sample_img', models.ImageField(upload_to='images/')),
                ('sample_label', models.CharField(blank=True, default=None, max_length=10, null=True)),
            ],
            options={
                'verbose_name_plural': 'Classify and Learn Samples Set 1',
            },
        ),
        migrations.CreateModel(
            name='Classify_And_Learn_Samples_set2',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sample_img', models.ImageField(upload_to='images/')),
                ('sample_label', models.CharField(blank=True, default=None, max_length=10, null=True)),
            ],
            options={
                'verbose_name_plural': 'Classify and Learn Samples Set 2',
            },
        ),
        migrations.CreateModel(
            name='Classify_And_Learn_Samples_set3',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sample_img', models.ImageField(upload_to='images/')),
                ('sample_label', models.CharField(blank=True, default=None, max_length=10, null=True)),
            ],
            options={
                'verbose_name_plural': 'Classify and Learn Samples Set 3',
            },
        ),
        migrations.CreateModel(
            name='Classify_And_Learn_Samples_set4',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sample_img', models.ImageField(upload_to='images/')),
                ('sample_label', models.CharField(blank=True, default=None, max_length=10, null=True)),
            ],
            options={
                'verbose_name_plural': 'Classify and Learn Samples Set 4',
            },
        ),
        migrations.CreateModel(
            name='Classify_And_Learn_Samples_set5',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sample_img', models.ImageField(upload_to='images/')),
                ('sample_label', models.CharField(blank=True, default=None, max_length=10, null=True)),
            ],
            options={
                'verbose_name_plural': 'Classify and Learn Samples Set 5',
            },
        ),
        migrations.CreateModel(
            name='Common_Features_Test_set1',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sample_img', models.ImageField(upload_to='images/')),
            ],
            options={
                'verbose_name_plural': 'Common Features Test Samples Set 1',
            },
        ),
        migrations.CreateModel(
            name='Common_Features_Test_set2',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sample_img', models.ImageField(upload_to='images/')),
            ],
            options={
                'verbose_name_plural': 'Common Features Test Samples Set 2',
            },
        ),
        migrations.CreateModel(
            name='Common_Features_Test_set3',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sample_img', models.ImageField(upload_to='images/')),
            ],
            options={
                'verbose_name_plural': 'Common Features Test Samples Set 3',
            },
        ),
        migrations.CreateModel(
            name='Common_Features_Test_set4',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sample_img', models.ImageField(upload_to='images/')),
            ],
            options={
                'verbose_name_plural': 'Common Features Test Samples Set 4',
            },
        ),
        migrations.CreateModel(
            name='Common_Features_Test_set5',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sample_img', models.ImageField(upload_to='images/')),
            ],
            options={
                'verbose_name_plural': 'Common Features Test Samples Set 5',
            },
        ),
        migrations.CreateModel(
            name='Observe_And_Learn_Samples_set1',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sample_img', models.ImageField(upload_to='images/')),
                ('sample_label', models.CharField(blank=True, default=None, max_length=10, null=True)),
            ],
            options={
                'verbose_name_plural': 'Observe and Learn Samples Set 1',
            },
        ),
        migrations.CreateModel(
            name='Observe_And_Learn_Samples_set2',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sample_img', models.ImageField(upload_to='images/')),
                ('sample_label', models.CharField(blank=True, default=None, max_length=10, null=True)),
            ],
            options={
                'verbose_name_plural': 'Observe and Learn Samples Set 2',
            },
        ),
        migrations.CreateModel(
            name='Observe_And_Learn_Samples_set3',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sample_img', models.ImageField(upload_to='images/')),
                ('sample_label', models.CharField(blank=True, default=None, max_length=10, null=True)),
            ],
            options={
                'verbose_name_plural': 'Observe and Learn Samples Set 3',
            },
        ),
        migrations.CreateModel(
            name='Observe_And_Learn_Samples_set4',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sample_img', models.ImageField(upload_to='images/')),
                ('sample_label', models.CharField(blank=True, default=None, max_length=10, null=True)),
            ],
            options={
                'verbose_name_plural': 'Observe and Learn Samples Set 4',
            },
        ),
        migrations.CreateModel(
            name='Observe_And_Learn_Samples_set5',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sample_img', models.ImageField(upload_to='images/')),
                ('sample_label', models.CharField(blank=True, default=None, max_length=10, null=True)),
            ],
            options={
                'verbose_name_plural': 'Observe and Learn Samples Set 5',
            },
        ),
        migrations.CreateModel(
            name='Test_set1',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sample_img', models.ImageField(upload_to='images/')),
                ('sample_label', models.CharField(blank=True, default=None, max_length=10, null=True)),
            ],
            options={
                'verbose_name_plural': 'Test Samples Set 1',
            },
        ),
        migrations.CreateModel(
            name='Test_set2',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sample_img', models.ImageField(upload_to='images/')),
                ('sample_label', models.CharField(blank=True, default=None, max_length=10, null=True)),
            ],
            options={
                'verbose_name_plural': 'Test Samples Set 2',
            },
        ),
        migrations.CreateModel(
            name='Test_set3',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sample_img', models.ImageField(upload_to='images/')),
                ('sample_label', models.CharField(blank=True, default=None, max_length=10, null=True)),
            ],
            options={
                'verbose_name_plural': 'Test Samples Set 3',
            },
        ),
        migrations.CreateModel(
            name='Test_set4',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sample_img', models.ImageField(upload_to='images/')),
                ('sample_label', models.CharField(blank=True, default=None, max_length=10, null=True)),
            ],
            options={
                'verbose_name_plural': 'Test Samples Set 4',
            },
        ),
        migrations.CreateModel(
            name='Test_set5',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sample_img', models.ImageField(upload_to='images/')),
                ('sample_label', models.CharField(blank=True, default=None, max_length=10, null=True)),
            ],
            options={
                'verbose_name_plural': 'Test Samples Set 5',
            },
        ),
        migrations.CreateModel(
            name='UserResponse_Common_Features_Test_set1',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_option', models.CharField(default=None, max_length=10)),
                ('iteration', models.IntegerField(default=1)),
                ('quid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='QuestionnaireColorCue.Common_Features_Test_set1')),
            ],
            options={
                'verbose_name_plural': 'User Response for Common Features Test phase set 1',
            },
        ),
        migrations.CreateModel(
            name='UserResponse_Common_Features_Test_set2',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_option', models.CharField(default=None, max_length=10)),
                ('iteration', models.IntegerField(default=1)),
                ('quid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='QuestionnaireColorCue.Common_Features_Test_set2')),
            ],
            options={
                'verbose_name_plural': 'User Response for Common Features Test phase set 2',
            },
        ),
        migrations.CreateModel(
            name='UserResponse_Common_Features_Test_set3',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_option', models.CharField(default=None, max_length=10)),
                ('iteration', models.IntegerField(default=1)),
                ('quid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='QuestionnaireColorCue.Common_Features_Test_set3')),
            ],
            options={
                'verbose_name_plural': 'User Response for Common Features Test phase set 3',
            },
        ),
        migrations.CreateModel(
            name='UserResponse_Common_Features_Test_set4',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_option', models.CharField(default=None, max_length=10)),
                ('iteration', models.IntegerField(default=1)),
                ('quid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='QuestionnaireColorCue.Common_Features_Test_set4')),
            ],
            options={
                'verbose_name_plural': 'User Response for Common Features Test phase set 4',
            },
        ),
        migrations.CreateModel(
            name='UserResponse_Common_Features_Test_set5',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_option', models.CharField(default=None, max_length=10)),
                ('iteration', models.IntegerField(default=1)),
                ('quid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='QuestionnaireColorCue.Common_Features_Test_set5')),
            ],
            options={
                'verbose_name_plural': 'User Response for Common Features Test phase set 5',
            },
        ),
        migrations.CreateModel(
            name='UserResponse_Test_set1',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_option', models.CharField(default=None, max_length=10)),
                ('iteration', models.IntegerField(default=1)),
                ('quid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='QuestionnaireColorCue.Test_set1')),
            ],
            options={
                'verbose_name_plural': 'User Response for Test phase set 1',
            },
        ),
        migrations.CreateModel(
            name='UserResponse_Test_set2',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_option', models.CharField(default=None, max_length=10)),
                ('iteration', models.IntegerField(default=1)),
                ('quid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='QuestionnaireColorCue.Test_set2')),
            ],
            options={
                'verbose_name_plural': 'User Response for Test phase set 2',
            },
        ),
        migrations.CreateModel(
            name='UserResponse_Test_set3',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_option', models.CharField(default=None, max_length=10)),
                ('iteration', models.IntegerField(default=1)),
                ('quid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='QuestionnaireColorCue.Test_set3')),
            ],
            options={
                'verbose_name_plural': 'User Response for Test phase set 3',
            },
        ),
        migrations.CreateModel(
            name='UserResponse_Test_set4',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_option', models.CharField(default=None, max_length=10)),
                ('iteration', models.IntegerField(default=1)),
                ('quid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='QuestionnaireColorCue.Test_set4')),
            ],
            options={
                'verbose_name_plural': 'User Response for Test phase set 4',
            },
        ),
        migrations.CreateModel(
            name='UserResponse_Test_set5',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_option', models.CharField(default=None, max_length=10)),
                ('iteration', models.IntegerField(default=1)),
                ('quid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='QuestionnaireColorCue.Test_set5')),
            ],
            options={
                'verbose_name_plural': 'User Response for Test phase set 5',
            },
        ),
        migrations.CreateModel(
            name='UserResponsesForDescription',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(blank=True, default=None, null=True)),
                ('set_number', models.CharField(blank=True, default=None, max_length=10, null=True)),
            ],
            options={
                'verbose_name_plural': 'User Responses for Description',
            },
        ),
        migrations.RemoveField(
            model_name='setnumber',
            name='user',
        ),
        migrations.AlterModelOptions(
            name='userdetails',
            options={'verbose_name_plural': 'User Details'},
        ),
        migrations.AddField(
            model_name='userdetails',
            name='set_num',
            field=models.CharField(blank=True, default=None, max_length=10, null=True),
        ),
        migrations.DeleteModel(
            name='SetNumber',
        ),
        migrations.AddField(
            model_name='userresponsesfordescription',
            name='user',
            field=models.ForeignKey(blank=True, default=None, on_delete=django.db.models.deletion.CASCADE, to='QuestionnaireColorCue.UserDetails'),
        ),
        migrations.AddField(
            model_name='userresponse_test_set5',
            name='user',
            field=models.ForeignKey(blank=True, default=None, on_delete=django.db.models.deletion.CASCADE, to='QuestionnaireColorCue.UserDetails'),
        ),
        migrations.AddField(
            model_name='userresponse_test_set4',
            name='user',
            field=models.ForeignKey(blank=True, default=None, on_delete=django.db.models.deletion.CASCADE, to='QuestionnaireColorCue.UserDetails'),
        ),
        migrations.AddField(
            model_name='userresponse_test_set3',
            name='user',
            field=models.ForeignKey(blank=True, default=None, on_delete=django.db.models.deletion.CASCADE, to='QuestionnaireColorCue.UserDetails'),
        ),
        migrations.AddField(
            model_name='userresponse_test_set2',
            name='user',
            field=models.ForeignKey(blank=True, default=None, on_delete=django.db.models.deletion.CASCADE, to='QuestionnaireColorCue.UserDetails'),
        ),
        migrations.AddField(
            model_name='userresponse_test_set1',
            name='user',
            field=models.ForeignKey(blank=True, default=None, on_delete=django.db.models.deletion.CASCADE, to='QuestionnaireColorCue.UserDetails'),
        ),
        migrations.AddField(
            model_name='userresponse_common_features_test_set5',
            name='user',
            field=models.ForeignKey(blank=True, default=None, on_delete=django.db.models.deletion.CASCADE, to='QuestionnaireColorCue.UserDetails'),
        ),
        migrations.AddField(
            model_name='userresponse_common_features_test_set4',
            name='user',
            field=models.ForeignKey(blank=True, default=None, on_delete=django.db.models.deletion.CASCADE, to='QuestionnaireColorCue.UserDetails'),
        ),
        migrations.AddField(
            model_name='userresponse_common_features_test_set3',
            name='user',
            field=models.ForeignKey(blank=True, default=None, on_delete=django.db.models.deletion.CASCADE, to='QuestionnaireColorCue.UserDetails'),
        ),
        migrations.AddField(
            model_name='userresponse_common_features_test_set2',
            name='user',
            field=models.ForeignKey(blank=True, default=None, on_delete=django.db.models.deletion.CASCADE, to='QuestionnaireColorCue.UserDetails'),
        ),
        migrations.AddField(
            model_name='userresponse_common_features_test_set1',
            name='user',
            field=models.ForeignKey(blank=True, default=None, on_delete=django.db.models.deletion.CASCADE, to='QuestionnaireColorCue.UserDetails'),
        ),
    ]
