# Generated by Django 2.0.2 on 2020-05-20 22:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Classify_And_Learn_Samples_set1',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sample_img', models.ImageField(upload_to='images/')),
                ('sample_label', models.CharField(blank=True, default=None, max_length=10, null=True)),
            ],
            options={
                'verbose_name_plural': 'Classify and Learn Samples Set 1',
            },
        ),
        migrations.CreateModel(
            name='Classify_And_Learn_Samples_set2',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sample_img', models.ImageField(upload_to='images/')),
                ('sample_label', models.CharField(blank=True, default=None, max_length=10, null=True)),
            ],
            options={
                'verbose_name_plural': 'Classify and Learn Samples Set 2',
            },
        ),
        migrations.CreateModel(
            name='Classify_And_Learn_Samples_set3',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sample_img', models.ImageField(upload_to='images/')),
                ('sample_label', models.CharField(blank=True, default=None, max_length=10, null=True)),
            ],
            options={
                'verbose_name_plural': 'Classify and Learn Samples Set 3',
            },
        ),
        migrations.CreateModel(
            name='Classify_And_Learn_Samples_set4',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sample_img', models.ImageField(upload_to='images/')),
                ('sample_label', models.CharField(blank=True, default=None, max_length=10, null=True)),
            ],
            options={
                'verbose_name_plural': 'Classify and Learn Samples Set 4',
            },
        ),
        migrations.CreateModel(
            name='Classify_And_Learn_Samples_set5',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sample_img', models.ImageField(upload_to='images/')),
                ('sample_label', models.CharField(blank=True, default=None, max_length=10, null=True)),
            ],
            options={
                'verbose_name_plural': 'Classify and Learn Samples Set 5',
            },
        ),
        migrations.CreateModel(
            name='Observe_And_Learn_Samples_set1',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sample_img', models.ImageField(upload_to='images/')),
                ('sample_label', models.CharField(blank=True, default=None, max_length=10, null=True)),
            ],
            options={
                'verbose_name_plural': 'Observe and Learn Samples Set 1',
            },
        ),
        migrations.CreateModel(
            name='Observe_And_Learn_Samples_set2',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sample_img', models.ImageField(upload_to='images/')),
                ('sample_label', models.CharField(blank=True, default=None, max_length=10, null=True)),
            ],
            options={
                'verbose_name_plural': 'Observe and Learn Samples Set 2',
            },
        ),
        migrations.CreateModel(
            name='Observe_And_Learn_Samples_set3',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sample_img', models.ImageField(upload_to='images/')),
                ('sample_label', models.CharField(blank=True, default=None, max_length=10, null=True)),
            ],
            options={
                'verbose_name_plural': 'Observe and Learn Samples Set 3',
            },
        ),
        migrations.CreateModel(
            name='Observe_And_Learn_Samples_set4',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sample_img', models.ImageField(upload_to='images/')),
                ('sample_label', models.CharField(blank=True, default=None, max_length=10, null=True)),
            ],
            options={
                'verbose_name_plural': 'Observe and Learn Samples Set 4',
            },
        ),
        migrations.CreateModel(
            name='Observe_And_Learn_Samples_set5',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sample_img', models.ImageField(upload_to='images/')),
                ('sample_label', models.CharField(blank=True, default=None, max_length=10, null=True)),
            ],
            options={
                'verbose_name_plural': 'Observe and Learn Samples Set 5',
            },
        ),
        migrations.CreateModel(
            name='SetNumber',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('set_num', models.CharField(blank=True, default=None, max_length=10, null=True)),
            ],
            options={
                'verbose_name_plural': 'Set Number',
            },
        ),
        migrations.CreateModel(
            name='Test_set1',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sample_img', models.ImageField(upload_to='images/')),
                ('sample_label', models.CharField(blank=True, default=None, max_length=10, null=True)),
            ],
            options={
                'verbose_name_plural': 'Test Samples Set 1',
            },
        ),
        migrations.CreateModel(
            name='Test_set2',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sample_img', models.ImageField(upload_to='images/')),
                ('sample_label', models.CharField(blank=True, default=None, max_length=10, null=True)),
            ],
            options={
                'verbose_name_plural': 'Test Samples Set 2',
            },
        ),
        migrations.CreateModel(
            name='Test_set3',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sample_img', models.ImageField(upload_to='images/')),
                ('sample_label', models.CharField(blank=True, default=None, max_length=10, null=True)),
            ],
            options={
                'verbose_name_plural': 'Test Samples Set 3',
            },
        ),
        migrations.CreateModel(
            name='Test_set4',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sample_img', models.ImageField(upload_to='images/')),
                ('sample_label', models.CharField(blank=True, default=None, max_length=10, null=True)),
            ],
            options={
                'verbose_name_plural': 'Test Samples Set 4',
            },
        ),
        migrations.CreateModel(
            name='Test_set5',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sample_img', models.ImageField(upload_to='images/')),
                ('sample_label', models.CharField(blank=True, default=None, max_length=10, null=True)),
            ],
            options={
                'verbose_name_plural': 'Test Samples Set 5',
            },
        ),
        migrations.CreateModel(
            name='UserDetails',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(blank=True, default=None, max_length=100, null=True)),
                ('last_name', models.CharField(blank=True, default=None, max_length=100, null=True)),
                ('email', models.EmailField(max_length=254)),
                ('gender', models.CharField(blank=True, default=None, max_length=10, null=True)),
                ('city', models.CharField(blank=True, default=None, max_length=100, null=True)),
                ('country', models.CharField(blank=True, default=None, max_length=100, null=True)),
                ('age', models.IntegerField(blank=True, default=None, null=True)),
            ],
            options={
                'verbose_name_plural': 'User Details',
            },
        ),
        migrations.CreateModel(
            name='UserResponse_Test_set1',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_option', models.CharField(default=None, max_length=10)),
                ('iteration', models.IntegerField(default=1)),
                ('quid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Questionnaire.Test_set1')),
            ],
            options={
                'verbose_name_plural': 'User Response for Test phase set 1',
            },
        ),
        migrations.CreateModel(
            name='UserResponse_Test_set2',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_option', models.CharField(default=None, max_length=10)),
                ('iteration', models.IntegerField(default=1)),
                ('quid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Questionnaire.Test_set2')),
            ],
            options={
                'verbose_name_plural': 'User Response for Test phase set 2',
            },
        ),
        migrations.CreateModel(
            name='UserResponse_Test_set3',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_option', models.CharField(default=None, max_length=10)),
                ('iteration', models.IntegerField(default=1)),
                ('quid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Questionnaire.Test_set3')),
            ],
            options={
                'verbose_name_plural': 'User Response for Test phase set 3',
            },
        ),
        migrations.CreateModel(
            name='UserResponse_Test_set4',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_option', models.CharField(default=None, max_length=10)),
                ('iteration', models.IntegerField(default=1)),
                ('quid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Questionnaire.Test_set4')),
            ],
            options={
                'verbose_name_plural': 'User Response for Test phase set 4',
            },
        ),
        migrations.CreateModel(
            name='UserResponse_Test_set5',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_option', models.CharField(default=None, max_length=10)),
                ('iteration', models.IntegerField(default=1)),
                ('quid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Questionnaire.Test_set5')),
            ],
            options={
                'verbose_name_plural': 'User Response for Test phase set 5',
            },
        ),
        migrations.AddField(
            model_name='setnumber',
            name='user',
            field=models.ForeignKey(blank=True, default=None, on_delete=django.db.models.deletion.CASCADE, to='Questionnaire.UserDetails'),
        ),
    ]
