# Generated by Django 2.0.2 on 2020-07-20 11:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Questionnaire', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userresponse_common_features_test_set1',
            name='time_taken',
        ),
        migrations.RemoveField(
            model_name='userresponse_common_features_test_set2',
            name='time_taken',
        ),
        migrations.RemoveField(
            model_name='userresponse_common_features_test_set3',
            name='time_taken',
        ),
        migrations.RemoveField(
            model_name='userresponse_common_features_test_set4',
            name='time_taken',
        ),
        migrations.RemoveField(
            model_name='userresponse_test_set1',
            name='time_taken',
        ),
        migrations.RemoveField(
            model_name='userresponse_test_set2',
            name='time_taken',
        ),
        migrations.RemoveField(
            model_name='userresponse_test_set3',
            name='time_taken',
        ),
        migrations.RemoveField(
            model_name='userresponse_test_set4',
            name='time_taken',
        ),
        migrations.RemoveField(
            model_name='userresponse_test_set5',
            name='time_taken',
        ),
    ]
