# Generated by Django 2.0.2 on 2020-07-09 09:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Questionnaire', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Common_Features_Test_set1',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sample_img', models.ImageField(upload_to='images/')),
            ],
            options={
                'verbose_name_plural': 'Common Features Test Samples Set 1',
            },
        ),
        migrations.CreateModel(
            name='Common_Features_Test_set2',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sample_img', models.ImageField(upload_to='images/')),
            ],
            options={
                'verbose_name_plural': 'Common Features Test Samples Set 2',
            },
        ),
        migrations.CreateModel(
            name='Common_Features_Test_set3',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sample_img', models.ImageField(upload_to='images/')),
            ],
            options={
                'verbose_name_plural': 'Common Features Test Samples Set 3',
            },
        ),
        migrations.CreateModel(
            name='Common_Features_Test_set4',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sample_img', models.ImageField(upload_to='images/')),
            ],
            options={
                'verbose_name_plural': 'Common Features Test Samples Set 4',
            },
        ),
        migrations.CreateModel(
            name='Common_Features_Test_set5',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sample_img', models.ImageField(upload_to='images/')),
            ],
            options={
                'verbose_name_plural': 'Common Features Test Samples Set 5',
            },
        ),
        migrations.CreateModel(
            name='UserResponse_Common_Features_Test_set1',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_option', models.CharField(default=None, max_length=10)),
                ('iteration', models.IntegerField(default=1)),
                ('quid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Questionnaire.Test_set1')),
            ],
            options={
                'verbose_name_plural': 'User Response for Common Features Test phase set 1',
            },
        ),
        migrations.CreateModel(
            name='UserResponse_Common_Features_Test_set2',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_option', models.CharField(default=None, max_length=10)),
                ('iteration', models.IntegerField(default=1)),
                ('quid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Questionnaire.Test_set2')),
            ],
            options={
                'verbose_name_plural': 'User Response for Common Features Test phase set 2',
            },
        ),
        migrations.CreateModel(
            name='UserResponse_Common_Features_Test_set3',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_option', models.CharField(default=None, max_length=10)),
                ('iteration', models.IntegerField(default=1)),
                ('quid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Questionnaire.Test_set3')),
            ],
            options={
                'verbose_name_plural': 'User Response for Common Features Test phase set 3',
            },
        ),
        migrations.CreateModel(
            name='UserResponse_Common_Features_Test_set4',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_option', models.CharField(default=None, max_length=10)),
                ('iteration', models.IntegerField(default=1)),
                ('quid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Questionnaire.Test_set4')),
            ],
            options={
                'verbose_name_plural': 'User Response for Common Features Test phase set 4',
            },
        ),
        migrations.CreateModel(
            name='UserResponse_Common_Features_Test_set5',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_option', models.CharField(default=None, max_length=10)),
                ('iteration', models.IntegerField(default=1)),
                ('quid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Questionnaire.Test_set5')),
            ],
            options={
                'verbose_name_plural': 'User Response for Common Features Test phase set 5',
            },
        ),
    ]
