# Generated by Django 2.0.2 on 2020-07-20 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Questionnaire', '0002_auto_20200720_1100'),
    ]

    operations = [
        migrations.AddField(
            model_name='userresponse_common_features_test_set1',
            name='time_taken',
            field=models.FloatField(default=None),
        ),
        migrations.AddField(
            model_name='userresponse_common_features_test_set2',
            name='time_taken',
            field=models.FloatField(default=None),
        ),
        migrations.AddField(
            model_name='userresponse_common_features_test_set3',
            name='time_taken',
            field=models.FloatField(default=None),
        ),
        migrations.AddField(
            model_name='userresponse_common_features_test_set4',
            name='time_taken',
            field=models.FloatField(default=None),
        ),
        migrations.AddField(
            model_name='userresponse_common_features_test_set5',
            name='time_taken',
            field=models.FloatField(default=None),
        ),
        migrations.AddField(
            model_name='userresponse_test_set1',
            name='time_taken',
            field=models.FloatField(default=None),
        ),
        migrations.AddField(
            model_name='userresponse_test_set2',
            name='time_taken',
            field=models.FloatField(default=None),
        ),
        migrations.AddField(
            model_name='userresponse_test_set3',
            name='time_taken',
            field=models.FloatField(default=None),
        ),
        migrations.AddField(
            model_name='userresponse_test_set4',
            name='time_taken',
            field=models.FloatField(default=None),
        ),
        migrations.AddField(
            model_name='userresponse_test_set5',
            name='time_taken',
            field=models.FloatField(default=None),
        ),
    ]
