# Generated by Django 2.0.2 on 2020-05-18 00:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Questionnaire', '0002_setnumber'),
    ]

    operations = [
        migrations.CreateModel(
            name='Observe_And_Learn_Samples',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sample_img', models.ImageField(upload_to='images/')),
                ('sample_label', models.CharField(blank=True, default=None, max_length=10, null=True)),
            ],
            options={
                'verbose_name_plural': 'Observe and Learn Samples',
            },
        ),
    ]
