# Generated by Django 2.0.2 on 2020-05-18 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Questionnaire', '0003_observe_and_learn_samples'),
    ]

    operations = [
        migrations.CreateModel(
            name='Observe_And_Learn_Samples_set2',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sample_img', models.ImageField(upload_to='images/')),
                ('sample_label', models.CharField(blank=True, default=None, max_length=10, null=True)),
            ],
            options={
                'verbose_name_plural': 'Observe and Learn Samples Set 2',
            },
        ),
        migrations.CreateModel(
            name='Observe_And_Learn_Samples_set3',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sample_img', models.ImageField(upload_to='images/')),
                ('sample_label', models.CharField(blank=True, default=None, max_length=10, null=True)),
            ],
            options={
                'verbose_name_plural': 'Observe and Learn Samples Set 3',
            },
        ),
        migrations.CreateModel(
            name='Observe_And_Learn_Samples_set4',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sample_img', models.ImageField(upload_to='images/')),
                ('sample_label', models.CharField(blank=True, default=None, max_length=10, null=True)),
            ],
            options={
                'verbose_name_plural': 'Observe and Learn Samples Set 4',
            },
        ),
        migrations.CreateModel(
            name='Observe_And_Learn_Samples_set5',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sample_img', models.ImageField(upload_to='images/')),
                ('sample_label', models.CharField(blank=True, default=None, max_length=10, null=True)),
            ],
            options={
                'verbose_name_plural': 'Observe and Learn Samples Set 5',
            },
        ),
        migrations.RenameModel(
            old_name='Observe_And_Learn_Samples',
            new_name='Observe_And_Learn_Samples_set1',
        ),
        migrations.AlterModelOptions(
            name='observe_and_learn_samples_set1',
            options={'verbose_name_plural': 'Observe and Learn Samples Set 1'},
        ),
    ]
