# Generated by Django 2.0.2 on 2020-07-09 11:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Questionnaire', '0003_userresponsesfordescription'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userresponsesfordescription',
            old_name='user_id',
            new_name='user',
        ),
        migrations.AddField(
            model_name='userresponse_common_features_test_set1',
            name='user',
            field=models.ForeignKey(blank=True, default=None, on_delete=django.db.models.deletion.CASCADE, to='Questionnaire.UserDetails'),
        ),
        migrations.AddField(
            model_name='userresponse_common_features_test_set2',
            name='user',
            field=models.ForeignKey(blank=True, default=None, on_delete=django.db.models.deletion.CASCADE, to='Questionnaire.UserDetails'),
        ),
        migrations.AddField(
            model_name='userresponse_common_features_test_set3',
            name='user',
            field=models.ForeignKey(blank=True, default=None, on_delete=django.db.models.deletion.CASCADE, to='Questionnaire.UserDetails'),
        ),
        migrations.AddField(
            model_name='userresponse_common_features_test_set4',
            name='user',
            field=models.ForeignKey(blank=True, default=None, on_delete=django.db.models.deletion.CASCADE, to='Questionnaire.UserDetails'),
        ),
        migrations.AddField(
            model_name='userresponse_common_features_test_set5',
            name='user',
            field=models.ForeignKey(blank=True, default=None, on_delete=django.db.models.deletion.CASCADE, to='Questionnaire.UserDetails'),
        ),
        migrations.AddField(
            model_name='userresponse_test_set1',
            name='user',
            field=models.ForeignKey(blank=True, default=None, on_delete=django.db.models.deletion.CASCADE, to='Questionnaire.UserDetails'),
        ),
        migrations.AddField(
            model_name='userresponse_test_set2',
            name='user',
            field=models.ForeignKey(blank=True, default=None, on_delete=django.db.models.deletion.CASCADE, to='Questionnaire.UserDetails'),
        ),
        migrations.AddField(
            model_name='userresponse_test_set3',
            name='user',
            field=models.ForeignKey(blank=True, default=None, on_delete=django.db.models.deletion.CASCADE, to='Questionnaire.UserDetails'),
        ),
        migrations.AddField(
            model_name='userresponse_test_set4',
            name='user',
            field=models.ForeignKey(blank=True, default=None, on_delete=django.db.models.deletion.CASCADE, to='Questionnaire.UserDetails'),
        ),
        migrations.AddField(
            model_name='userresponse_test_set5',
            name='user',
            field=models.ForeignKey(blank=True, default=None, on_delete=django.db.models.deletion.CASCADE, to='Questionnaire.UserDetails'),
        ),
        migrations.AlterField(
            model_name='userresponse_common_features_test_set1',
            name='quid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Questionnaire.Common_Features_Test_set1'),
        ),
        migrations.AlterField(
            model_name='userresponse_common_features_test_set2',
            name='quid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Questionnaire.Common_Features_Test_set2'),
        ),
        migrations.AlterField(
            model_name='userresponse_common_features_test_set3',
            name='quid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Questionnaire.Common_Features_Test_set3'),
        ),
        migrations.AlterField(
            model_name='userresponse_common_features_test_set4',
            name='quid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Questionnaire.Common_Features_Test_set4'),
        ),
        migrations.AlterField(
            model_name='userresponse_common_features_test_set5',
            name='quid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Questionnaire.Common_Features_Test_set5'),
        ),
    ]
