# Generated by Django 2.0.2 on 2020-07-20 11:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Questionnaire', '0003_auto_20200720_1101'),
    ]

    operations = [
        migrations.CreateModel(
            name='CommonFeatureTable',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('set_number', models.IntegerField(default=None)),
                ('block_number', models.IntegerField(default=None)),
                ('sequence_number', models.IntegerField(default=None)),
                ('file_name', models.CharField(default=None, max_length=150)),
                ('user_option', models.CharField(default=None, max_length=10)),
                ('correct_option', models.CharField(default=None, max_length=10)),
                ('rule_based', models.IntegerField(default=None)),
                ('time_taken', models.FloatField(default=None)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Questionnaire.UserDetails')),
            ],
            options={
                'verbose_name_plural': 'Common Feature Test Table',
            },
        ),
        migrations.CreateModel(
            name='TransferStimuliTable',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('set_number', models.IntegerField(default=None)),
                ('block_number', models.IntegerField(default=None)),
                ('sequence_number', models.IntegerField(default=None)),
                ('file_name', models.CharField(default=None, max_length=150)),
                ('user_option', models.CharField(default=None, max_length=10)),
                ('rule_based', models.IntegerField(default=None)),
                ('time_taken', models.FloatField(default=None)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Questionnaire.UserDetails')),
            ],
            options={
                'verbose_name_plural': 'Transfer Stimuli Table',
            },
        ),
    ]
