# Generated by Django 2.0.2 on 2020-05-18 17:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Questionnaire', '0004_auto_20200518_0939'),
    ]

    operations = [
        migrations.CreateModel(
            name='Classify_And_Learn_Samples_set1',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sample_img', models.ImageField(upload_to='images/')),
                ('sample_label', models.CharField(blank=True, default=None, max_length=10, null=True)),
            ],
            options={
                'verbose_name_plural': 'Classify and Learn Samples Set 1',
            },
        ),
        migrations.CreateModel(
            name='Classify_And_Learn_Samples_set2',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sample_img', models.ImageField(upload_to='images/')),
                ('sample_label', models.CharField(blank=True, default=None, max_length=10, null=True)),
            ],
            options={
                'verbose_name_plural': 'Classify and Learn Samples Set 2',
            },
        ),
        migrations.CreateModel(
            name='Classify_And_Learn_Samples_set3',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sample_img', models.ImageField(upload_to='images/')),
                ('sample_label', models.CharField(blank=True, default=None, max_length=10, null=True)),
            ],
            options={
                'verbose_name_plural': 'Classify and Learn Samples Set 3',
            },
        ),
        migrations.CreateModel(
            name='Classify_And_Learn_Samples_set4',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sample_img', models.ImageField(upload_to='images/')),
                ('sample_label', models.CharField(blank=True, default=None, max_length=10, null=True)),
            ],
            options={
                'verbose_name_plural': 'Classify and Learn Samples Set 4',
            },
        ),
        migrations.CreateModel(
            name='Classify_And_Learn_Samples_set5',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sample_img', models.ImageField(upload_to='images/')),
                ('sample_label', models.CharField(blank=True, default=None, max_length=10, null=True)),
            ],
            options={
                'verbose_name_plural': 'Classify and Learn Samples Set 5',
            },
        ),
    ]
