# Generated by Django 2.0.2 on 2020-05-20 18:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Questionnaire', '0006_test_set1_test_set2_test_set3_test_set4_test_set5'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserResponse_Test',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_option', models.CharField(default=None, max_length=10)),
            ],
            options={
                'verbose_name_plural': 'User Response for Test phase',
            },
        ),
    ]
