# Generated by Django 2.0.2 on 2020-05-20 19:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Questionnaire', '0007_userresponse_test'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserResponse_Test_set1',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_option', models.CharField(default=None, max_length=10)),
                ('quid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Questionnaire.Test_set1')),
            ],
            options={
                'verbose_name_plural': 'User Response for Test phase set 1',
            },
        ),
        migrations.CreateModel(
            name='UserResponse_Test_set2',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_option', models.CharField(default=None, max_length=10)),
                ('quid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Questionnaire.Test_set1')),
            ],
            options={
                'verbose_name_plural': 'User Response for Test phase set 2',
            },
        ),
        migrations.CreateModel(
            name='UserResponse_Test_set3',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_option', models.CharField(default=None, max_length=10)),
                ('quid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Questionnaire.Test_set1')),
            ],
            options={
                'verbose_name_plural': 'User Response for Test phase set 3',
            },
        ),
        migrations.CreateModel(
            name='UserResponse_Test_set4',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_option', models.CharField(default=None, max_length=10)),
                ('quid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Questionnaire.Test_set1')),
            ],
            options={
                'verbose_name_plural': 'User Response for Test phase set 4',
            },
        ),
        migrations.CreateModel(
            name='UserResponse_Test_set5',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_option', models.CharField(default=None, max_length=10)),
                ('quid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Questionnaire.Test_set1')),
            ],
            options={
                'verbose_name_plural': 'User Response for Test phase set 5',
            },
        ),
        migrations.DeleteModel(
            name='UserResponse_Test',
        ),
    ]
