# Generated by Django 2.0.2 on 2020-08-08 21:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('QuestionnaireColorCueNew', '0005_auto_20200809_0313'),
    ]

    operations = [
        migrations.RenameField(
            model_name='commonfeaturetable',
            old_name='correct',
            new_name='rule_based',
        ),
        migrations.RemoveField(
            model_name='classifystimuitable',
            name='correct',
        ),
    ]
