# Generated by Django 2.0.2 on 2020-08-08 21:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('QuestionnaireColorCueNew', '0006_auto_20200809_0315'),
    ]

    operations = [
        migrations.RenameField(
            model_name='commonfeaturetable',
            old_name='rule_based',
            new_name='correct',
        ),
        migrations.AddField(
            model_name='classifystimuitable',
            name='correct',
            field=models.IntegerField(default=None),
        ),
    ]
