from django.contrib import admin
from .models import *

#User Details
admin.site.register(UserDetails)
admin.site.register(SetNumber)
admin.site.register(Observe_And_Learn_Samples_set1)
admin.site.register(Observe_And_Learn_Samples_set2)
admin.site.register(Observe_And_Learn_Samples_set3)
admin.site.register(Observe_And_Learn_Samples_set4)
admin.site.register(Observe_And_Learn_Samples_set5)
admin.site.register(Classify_And_Learn_Samples_set1)
admin.site.register(Classify_And_Learn_Samples_set2)
admin.site.register(Classify_And_Learn_Samples_set3)
admin.site.register(Classify_And_Learn_Samples_set4)
admin.site.register(Classify_And_Learn_Samples_set5)
admin.site.register(Test_set1)
admin.site.register(Test_set2)
admin.site.register(Test_set3)
admin.site.register(Test_set4)
admin.site.register(Test_set5)
admin.site.register(UserResponse_Test_set1)
admin.site.register(UserResponse_Test_set2)
admin.site.register(UserResponse_Test_set3)
admin.site.register(UserResponse_Test_set4)
admin.site.register(UserResponse_Test_set5)